name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.c"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"

jobs:

  cmake:
    strategy:
      matrix:
        shared: [true, false]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: cmake -B build -DCMAKE_INSTALL_PREFIX:PATH=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - name: Build
      run: cmake --build build --parallel

    - name: Test
      run: ctest --test-dir build --no-tests=error -V

    - name: Install
      run: cmake --install build
